name: Link branch to Jira
on:
  create:
    branches:
    tags-ignore: "*"

jobs:
  link-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira issue ID
        id: extract-issue
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          ISSUE_ID=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+')
          echo "issue_id=$ISSUE_ID" >> $GITHUB_OUTPUT

      - name: Link branch to Jira issue
        if: steps.extract-issue.outputs.issue_id != ''
        run: |
          curl -v -X POST "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract-issue.outputs.issue_id }}/remotelink" \
          -H "Authorization: Basic $(echo -n ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} | base64 -w 0)" \
          -H "Content-Type: application/json" \
          -d '{
            "object": {
              "url": "https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}",
              "title": "GitHub Branch: ${{ github.ref_name }}"
            }
          }'
